spring:
   datasource:
     url: jdbc:mysql://localhost:3306/xlch?useSSL=false
     username: root
     password: root

user:
   address: hello
#                  driverClassName:com.mysql.jdbc.Driver
#---
#spring:
#       profiles:development
#server:
#       address:127.0.0.1
#
#spring:
#       datasource:
#                  url:jdbc:mysql://localhost:3306/xlch?useSSL=false
#                  name:root
#                  password:root
#---
#spring:
#       profiles:production
#server:
#       address:172.16.60.138
#
#spring:
#       datasource:
#                  url:jdbc:mysql://localhost:3306/xlch?useSSL=false
#                  name:root
#                  password:root